### ISSUE TITLE
savefig pdf with ORCA v0.2.1, v0.3.0 and master

### ISSUE THREAD

**Issue by fipelle** [sglyon/ORCA.jl#23]
Hi, 

I noticed that there is an issue with saving charts in pdf with ```v0.3.0``` (pinning to ```v0.2.1``` or using ```master``` solves it for some reason). I tried both with a macbook and a windows machine.

The code below reproduces the error:
```julia
using PlotlyJS, ORCA;

# Chart
pp1=plot(scatter(y=rand(100)));

# Save (it works on 0.2.1 and master)
savefig(pp1, "aaa.pdf", format="pdf");

#=
In v0.3.0 -> ERROR: MethodError: PlotlyBase.savefig(::PlotlyJS.SyncPlot, ::String) is ambiguous.
I did not use savefig(pp1, "aaa.pdf") because it gives the same error in both v0.2.1, v0.3.0 and master.
=#
```

Can you please take a look at it?

**Comment by josephmarturano** [comment]
I have seen this too. For saving on v3.0, the `plot` function needs a capital 'p', as in `Plot`. Could you try the following:

```
using PlotlyJS, ORCA;
pp1 = Plot(scatter(y=rand(100)));
savefig(pp1, "aaa.pdf")
```

**Comment by fipelle** [comment]
This works better.

**Comment by sglyon** [comment]
Thanks for bringing this up. We'll get it fixed!

**Comment by sglyon** [comment]
Thanks @fipelle and @josephmarturano 

Due to the problems with this package, we have decided to go another direction. The savefig functionality offered by this package has been superseded by new routines built in to PlotlyBase.jl (and thus PlotlyJS.jl) itself.

ORCA.jl is now deprecated and should not be used going forward.

Thank you
