### ISSUE TITLE
Cannot run orca_cmd on Ubuntu

### ISSUE THREAD

**Issue by rasmushenningsson** [sglyon/ORCA.jl#36]
When running `using ORCA` it prints:
> /usr/bin/env: ‘node’: No such file or directory

Similarly, when calling savefig() on a PlotlyJS figure, it prints the same error and the plot is not saved.

It seems to me like this behavior appeared with #30. The problem seems to be that the `orca` executable is now a javascript file (`orca.js`) instead of a bash script like before. (Orca 0.3.1 still works for me.)

My guess is this can be solved by calling the orca_cmd with `nodejs_cmd` from NodeJS. That is, something like
``` `$nodejs_cmd $orca_cmd params` ```
on linux. (This might also apply to macos, but I cannot test on that platform.)

**Comment by sglyon** [comment]
Thank you @rasmushenningsson 

Due to the problems with this package, we have decided to go another direction. The savefig functionality offered by this package has been superseded by new routines built in to PlotlyBase.jl (and thus PlotlyJS.jl) itself.

ORCA.jl is now deprecated and should not be used going forward.

Thank you

**Comment by rasmushenningsson** [comment]
That sounds great. Thanks for all the effort!
