### ISSUE TITLE
Quoting issues in build.jl

### ISSUE THREAD

**Issue by david-macmahon** [sglyon/ORCA.jl#38]
Commit 4c646bcac added the quotes around `$(orca_cmd)` in line 24 (at the time) of `build.jl`:

```
println(f, "const orca_cmd = `\"$(orca_cmd)\"`")
```

This works great when `orca_cmd` is just a path (possibly containing spaces) to the `orca` executable.  Unfortunately, when installing in a container, `orca_cmd` is two words: the full path to `xvfb-run` and the full path to `orca`.  In the container case, the quotes cause the two words to be treated as a single word thereby making `orca_cmd` equivalent to trying to run the one-word command `"xvfb-run orca"` rather than the two-word command `"xvfb-run" "orca"` (fully qualified paths have been shortened here for clarity).  This prevents ORCA.jl from functioning properly.

I was able to get things working by removing the quotes, but that only worked because neither my `xvfb-run` command nor my `orca` command have spaces in their full path names, so obviously this isn't a general solution.  The quotes were added in 4c646bcac for a reason, but while solving one problem it seems to have created another.

**Comment by sglyon** [comment]
Thanks @david-macmahon 

Due to the problems with this package, we have decided to go another direction. The savefig functionality offered by this package has been superseded by new routines built in to PlotlyBase.jl (and thus PlotlyJS.jl) itself.

ORCA.jl is now deprecated and should not be used going forward.

Thank you
